apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-negaver-se-tls
spec:
  secretName: k8s-negaver-se
  issuerRed:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.negaver.se
  dnsNames:
    - k8s.negaver.se
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.negaver.se